import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.105.0/+esm';
import QRCode from 'https://cdn.jsdelivr.net/npm/qrcode@1.5.4/+esm';

const SUPABASE_URL='https://kgcuqxzpxykqszdeonte.supabase.co';
const SUPABASE_KEY='sb_publishable_I5X2IBZZkmFyDDez_Kf4aA_hNyLkzay';
const PRIVATE_FN=`${SUPABASE_URL}/functions/v1/tech-private`;
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,experimental:{passkey:true}}});
const app=document.getElementById('app'),toast=document.getElementById('toast'),modal=document.getElementById('modal'),modalBody=document.getElementById('modalBody');
let data=null,pending={};
const statusLabels={received:'Recibido',reviewing:'En revisión',contacted:'Contactado',processing:'Tramitando',pending_installation:'Pendiente de instalación',installed:'Instalado',validated:'Validado',not_completed:'No completado',duplicate:'Duplicado'};
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function showToast(msg){toast.textContent=msg;toast.hidden=false;clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.hidden=true,3200)}
function deviceLabel(){const ua=navigator.userAgent;return /iPhone|iPad/.test(ua)?'iPhone / iPad':/Android/.test(ua)?'Android':/Windows/.test(ua)?'Windows':/Mac/.test(ua)?'Mac':'Navegador';}
async function privateCall(action,extra={}){const{data:s}=await supabase.auth.getSession();const token=s.session?.access_token;if(!token)throw new Error('NO_SESSION');const r=await fetch(PRIVATE_FN,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY,'Authorization':`Bearer ${token}`},body:JSON.stringify({action,...extra})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'No se pudo completar la operación');return j;}
async function shareEvent(event_type,offer_slug=null){try{await privateCall('share_event',{event_type,offer_slug})}catch{}}
function offerUrl(o){return `https://www.fibaroteleco.com/top-tarifas/?r=${encodeURIComponent(data.profile.public_code)}${o?`&o=${encodeURIComponent(o.slug)}`:''}`}
function storefrontUrl(){return offerUrl(null)}
function badgeClass(s){return s==='validated'?'ok':(s==='not_completed'||s==='duplicate')?'bad':'warn'}
function renderAuth(step='phone',message=''){
  const stored=JSON.parse(sessionStorage.getItem('tech_pending')||'{}'); pending={...stored,...pending};
  app.innerHTML=`<section class="auth"><div class="authCard"><div class="authLogo">T</div><div class="eyebrow" style="color:#1769ff">TOP TARIFAS</div><h1>Crea tu enlace personal.</h1><p>Te identificamos en segundos para que cada solicitud que llegue desde tus enlaces y QR quede asociada a ti. Sin contraseñas.</p>${step==='phone'?`<div class="field"><label>Nombre o alias</label><input id="a-name" autocomplete="name" placeholder="Ej. Juan Carlos o JaviFiber" value="${esc(pending.name||'')}"></div><div class="field"><label>Móvil</label><div class="phoneWrap"><div class="prefix">+34</div><input id="a-phone" inputmode="tel" autocomplete="tel-national" placeholder="600 000 000" value="${esc(pending.phone||'')}"></div></div><button class="btn primary" id="sendOtp" style="width:100%">Recibir código</button>`:`<div class="field"><label>Código enviado al ${esc(pending.phone||'móvil')}</label><input id="a-otp" class="otp" inputmode="numeric" autocomplete="one-time-code" maxlength="6" placeholder="••••••"></div><button class="btn primary" id="verifyOtp" style="width:100%">Entrar</button><button class="btn" id="backPhone" style="width:100%;margin-top:8px">Cambiar número</button>`}<div id="authStatus" class="authStatus ${message?'error':''}">${esc(message)}</div><div class="divider"></div><div class="privacyNote">Tu código público de referido es distinto de tus credenciales de acceso. Nadie puede entrar en tu cuenta con tu QR o enlace. Mantendremos tu sesión en este dispositivo hasta que cierres sesión.</div></div></section>`;
  if(step==='phone')document.getElementById('sendOtp').onclick=sendOtp;else{document.getElementById('verifyOtp').onclick=verifyOtp;document.getElementById('backPhone').onclick=()=>renderAuth('phone')}
}
async function sendOtp(){
  const name=document.getElementById('a-name').value.trim(),digits=document.getElementById('a-phone').value.replace(/\D/g,'');const st=document.getElementById('authStatus');
  if(name.length<2){st.textContent='Indica tu nombre o alias.';st.className='authStatus error';return}if(digits.length!==9){st.textContent='Indica un móvil español de 9 cifras.';st.className='authStatus error';return}
  pending={name,phone:digits};sessionStorage.setItem('tech_pending',JSON.stringify(pending));st.textContent='Enviando código…';st.className='authStatus';
  const{error}=await supabase.auth.signInWithOtp({phone:`+34${digits}`});
  if(error){const m=/provider|sms|phone/i.test(error.message)?'El envío por SMS todavía no está disponible. FÍBARO debe activar el proveedor de SMS del proyecto antes del primer acceso real.':error.message;st.textContent=m;st.className='authStatus error';return}
  renderAuth('otp');
}
async function verifyOtp(){const token=document.getElementById('a-otp').value.replace(/\D/g,'');const st=document.getElementById('authStatus');if(token.length!==6){st.textContent='El código tiene 6 cifras.';st.className='authStatus error';return}st.textContent='Verificando…';const{error}=await supabase.auth.verifyOtp({phone:`+34${pending.phone}`,token,type:'sms'});if(error){st.textContent=error.message;st.className='authStatus error';return}sessionStorage.removeItem('tech_pending');await load(true);}
async function load(first=false){app.innerHTML='<div class="loading">Cargando tu espacio…</div>';try{data=await privateCall('bootstrap',{device_label:deviceLabel()});if(first&&pending.name&&!data.profile.full_name){const isAlias=!pending.name.includes(' ');await privateCall('update_profile',{profile:{full_name:pending.name,alias:isAlias?pending.name:'',email:'',company:'',province:'',city:'',bio:'',specialties:[]}});data=await privateCall('dashboard');}renderDashboard();}catch(e){if(e.message==='NO_SESSION'||/sesión/i.test(e.message))renderAuth();else app.innerHTML=`<div class="card"><h2>No se pudo abrir Top Tarifas</h2><p class="muted">${esc(e.message)}</p><button class="btn" id="retry">Reintentar</button></div>`,document.getElementById('retry').onclick=()=>load();}}
function renderDashboard(){
  const p=data.profile,alias=p.alias||p.full_name||'Técnico';
  app.innerHTML=`<section class="hero"><div class="heroTop"><div><div class="eyebrow">TU CANAL DE OPORTUNIDADES</div><h1>Comparte. Nosotros<br>gestionamos el resto.</h1><p>Elige una Top Tarifa, compártela con tu enlace o QR y sigue desde aquí cada solicitud que llegue referida por ti.</p></div><div class="profileMini"><b>${esc(alias)}</b><small>${esc(p.public_code)}</small><div class="actions" style="justify-content:flex-end"><button class="btn" data-profile>Mi perfil</button></div></div></div><div class="stats"><div class="stat"><strong>${data.counts.total}</strong><span>Referencias</span></div><div class="stat"><strong>${data.counts.validated}</strong><span>Validadas</span></div><div class="stat"><strong>${data.counts.in_process}</strong><span>En proceso</span></div><div class="stat"><strong>${data.metrics.opens}</strong><span>Aperturas</span></div></div></section>
  <div class="grid2"><section class="card"><h2>Mi escaparate</h2><div class="muted">Un único enlace permanente con las Top Tarifas activas. Puedes ponerlo en tu bio o enviarlo a cualquiera.</div><div class="linkbox"><code>${esc(storefrontUrl())}</code><button class="btn" data-copy-store>Copiar</button></div><div class="actions"><button class="btn primary" data-share-store>Compartir</button><button class="btn" data-qr-store>Mostrar QR</button></div></section><section class="card"><h2>Tu seguimiento</h2><div class="muted">Tus referencias quedan protegidas. Si el mismo cliente vuelve a solicitar dentro de 30 días, se conserva la primera atribución.</div><div class="actions"><button class="btn soft" data-scroll-ref>Ver mis referencias</button><button class="btn" data-security>Seguridad</button></div></section></div>
  <div class="offersHeader"><div><div class="eyebrow" style="color:#1769ff">SELECCIÓN ACTUAL</div><h2>Top Tarifas</h2></div><div class="muted">Alicia actualiza ofertas y creatividades.</div></div><section class="offers">${data.offers.map(renderOffer).join('')}</section>
  <section class="card" id="refs" style="margin-top:22px"><h2>Mis referencias</h2><div class="muted">Verás el avance comercial sin datos internos ni información sensible innecesaria.</div><div class="refList">${data.referrals.length?data.referrals.map(r=>`<div class="refRow"><div><b>${esc(r.offer_title)} · ${esc(r.customer_name)}</b><div class="refMeta">${esc(r.referral_code)} · ${new Date(r.created_at).toLocaleDateString('es-ES')}${r.status_reason?` · ${esc(r.status_reason)}`:''}</div></div><span class="badge ${badgeClass(r.status)}">${esc(statusLabels[r.status]||r.status)}</span></div>`).join(''):'<div class="empty">Todavía no tienes referencias. Comparte una Top Tarifa y aparecerán aquí cuando alguien la solicite.</div>'}</div></section>`;
  bindDashboard();
}
function renderOffer(o){const features=Array.isArray(o.features)?o.features:[];return `<article class="offer" style="--accent:${esc(o.accent||'#1769ff')}"><div class="offerTop"><div><div class="kicker">${esc(o.kicker||'TOP TARIFA')}</div><h3>${esc(o.title)}</h3><div class="company">${esc(o.company_name||'FÍBARO')}</div></div><div>${o.is_demo?'<span class="demo">DEMO</span>':''}${o.price_label?`<div class="price">${esc(o.price_label)}</div>`:''}</div></div><p>${esc(o.description)}</p><div class="features">${features.slice(0,4).map(f=>`<span class="pill">${esc(f)}</span>`).join('')}</div><div class="muted">${esc(o.contract_company_label||'FÍBARO asesora y gestiona; el contrato se realiza con la operadora seleccionada.')}</div><div class="actions"><button class="btn primary" data-share="${esc(o.slug)}">Compartir</button><button class="btn" data-wa="${esc(o.slug)}">WhatsApp</button><button class="btn" data-story="${esc(o.slug)}">Story / Estado</button><button class="btn" data-qr="${esc(o.slug)}">QR</button></div></article>`}
function getOffer(slug){return data.offers.find(x=>x.slug===slug)}
function bindDashboard(){
  document.querySelector('[data-profile]').onclick=openProfile;document.querySelector('[data-copy-store]').onclick=()=>copy(storefrontUrl(),'copy');document.querySelector('[data-share-store]').onclick=()=>nativeShare(null);document.querySelector('[data-qr-store]').onclick=()=>openQR(null);document.querySelector('[data-scroll-ref]').onclick=()=>document.getElementById('refs').scrollIntoView({behavior:'smooth'});document.querySelector('[data-security]').onclick=openSecurity;
  document.querySelectorAll('[data-share]').forEach(b=>b.onclick=()=>nativeShare(getOffer(b.dataset.share)));document.querySelectorAll('[data-wa]').forEach(b=>b.onclick=()=>shareWhatsApp(getOffer(b.dataset.wa)));document.querySelectorAll('[data-story]').forEach(b=>b.onclick=()=>createStory(getOffer(b.dataset.story)));document.querySelectorAll('[data-qr]').forEach(b=>b.onclick=()=>openQR(getOffer(b.dataset.qr)));
}
async function copy(v,event='copy',o=null){await navigator.clipboard.writeText(v);showToast('Enlace copiado');shareEvent(event,o?.slug)}
async function nativeShare(o){const url=o?offerUrl(o):storefrontUrl(),txt=o?(o.social_text||o.whatsapp_text||o.description):'Estas son mis Top Tarifas de FÍBARO. Si alguna te interesa, puedes solicitarla desde mi enlace.';try{if(navigator.share){await navigator.share({title:o?.title||'Top Tarifas',text:txt,url});await shareEvent('share',o?.slug)}else await copy(`${txt}\n${url}`,'share',o)}catch(e){if(e.name!=='AbortError')await copy(`${txt}\n${url}`,'share',o)}}
function shareWhatsApp(o){const url=offerUrl(o),txt=`${o.whatsapp_text||o.description}\n${url}`;shareEvent('whatsapp',o.slug);window.open(`https://wa.me/?text=${encodeURIComponent(txt)}`,'_blank','noopener')}
async function openQR(o){const url=o?offerUrl(o):storefrontUrl();const c=document.createElement('canvas');await QRCode.toCanvas(c,url,{width:320,margin:2,errorCorrectionLevel:'M',color:{dark:'#071827',light:'#ffffff'}});modalBody.innerHTML=`<div class="qrbox"><div id="qrslot"></div><h3>${esc(o?.title||'Mi escaparate')}</h3><p>Escanea para abrir ${o?'esta oferta':'tus Top Tarifas'} con tu referencia ya incorporada.</p><div class="linkbox"><code>${esc(url)}</code></div><div class="actions" style="justify-content:center"><button class="btn primary" id="copyqr">Copiar enlace</button></div></div>`;document.getElementById('qrslot').appendChild(c);document.getElementById('copyqr').onclick=()=>copy(url,'qr',o);modal.hidden=false;shareEvent('qr',o?.slug)}
function loadImage(src){return new Promise((resolve,reject)=>{const im=new Image();im.crossOrigin='anonymous';im.onload=()=>resolve(im);im.onerror=reject;im.src=src})}
async function createStory(o){showToast('Preparando creatividad…');const url=offerUrl(o),canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1920;const x=canvas.getContext('2d');const grad=x.createLinearGradient(0,0,1080,1920);grad.addColorStop(0,o.accent||'#1769ff');grad.addColorStop(1,'#071827');x.fillStyle=grad;x.fillRect(0,0,1080,1920);
  if(o.story_image_url){try{const im=await loadImage(o.story_image_url);const s=Math.max(1080/im.width,1920/im.height);const w=im.width*s,h=im.height*s;x.globalAlpha=.52;x.drawImage(im,(1080-w)/2,(1920-h)/2,w,h);x.globalAlpha=1;x.fillStyle='rgba(7,24,39,.55)';x.fillRect(0,0,1080,1920)}catch{}}
  x.fillStyle='#56d8ff';x.font='800 30px Arial';x.fillText('TOP TARIFAS · FÍBARO',76,120);x.fillStyle='#fff';x.font='900 78px Arial';wrap(x,o.title,76,245,920,88);let yy=o.title.length>24?430:350;if(o.price_label){x.font='900 62px Arial';x.fillText(o.price_label,76,yy);yy+=90}x.font='700 32px Arial';x.fillStyle='#d9e5eb';wrap(x,o.company_name||'FÍBARO',76,yy,880,45);yy+=95;x.font='500 30px Arial';x.fillStyle='#e7eff3';wrap(x,o.description,76,yy,920,42);
  const qrData=await QRCode.toDataURL(url,{width:390,margin:2,errorCorrectionLevel:'M',color:{dark:'#071827',light:'#ffffff'}});const qim=await loadImage(qrData);x.fillStyle='#fff';roundRect(x,75,1290,930,510,32);x.fill();x.drawImage(qim,120,1340,360,360);x.fillStyle='#071827';x.font='900 39px Arial';x.fillText('Escanea y solicítala',525,1440);x.font='600 26px Arial';x.fillStyle='#48606f';wrap(x,'La solicitud queda vinculada a mi enlace de recomendación.',525,1500,420,38);x.font='700 23px Arial';wrap(x,`${o.contract_company_label||'FÍBARO asesora y gestiona la contratación.'}`,525,1620,420,34);x.fillStyle='#718590';x.font='600 22px Arial';x.fillText('fibaroteleco.com',525,1738);
  canvas.toBlob(async blob=>{if(!blob)return;const file=new File([blob],`top-tarifa-${o.slug}.jpg`,{type:'image/jpeg'});try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:o.title,text:o.social_text||o.description,url});await shareEvent('story',o.slug)}else{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file.name;a.click();await navigator.clipboard.writeText(url);await shareEvent('story',o.slug);showToast('Creatividad guardada y enlace copiado. Súbela a tu Estado/Story.')}}catch(e){if(e.name!=='AbortError')showToast('No se pudo abrir el menú de compartir.')}},'image/jpeg',.92);
}
function wrap(ctx,text,x,y,maxWidth,lineHeight){const words=String(text||'').split(' ');let line='';for(let n=0;n<words.length;n++){const test=line+words[n]+' ';if(ctx.measureText(test).width>maxWidth&&n>0){ctx.fillText(line.trim(),x,y);line=words[n]+' ';y+=lineHeight}else line=test}ctx.fillText(line.trim(),x,y);return y}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect?ctx.roundRect(x,y,w,h,r):(ctx.rect(x,y,w,h));}
function openProfile(){const p=data.profile;const specs=['Fibra','Móvil','Instalaciones','Averías','Empresas','Radio/4G/5G'];modalBody.innerHTML=`<h2>Mi perfil</h2><p class="muted">Tu perfil se completa de forma progresiva. No afecta a tus enlaces ya creados.</p><div class="profileForm"><div class="field"><label>Nombre y apellidos</label><input id="pf-name" value="${esc(p.full_name||'')}"></div><div class="field"><label>Alias público</label><input id="pf-alias" value="${esc(p.alias||'')}"></div><div class="field"><label>Email de contacto/recuperación</label><input id="pf-email" type="email" value="${esc(p.email||'')}"></div><div class="field"><label>Empresa</label><input id="pf-company" value="${esc(p.company||'')}"></div><div class="field"><label>Provincia</label><input id="pf-prov" value="${esc(p.province||'')}"></div><div class="field"><label>Población</label><input id="pf-city" value="${esc(p.city||'')}"></div><div class="wide field"><label>Especialidades</label><div class="checks">${specs.map(s=>`<label class="check"><input type="checkbox" value="${s}" ${(p.specialties||[]).includes(s)?'checked':''}>${s}</label>`).join('')}</div></div><div class="wide field"><label>Sobre ti</label><textarea id="pf-bio" rows="3" maxlength="600">${esc(p.bio||'')}</textarea></div></div><div class="actions"><button class="btn primary" id="saveProfile">Guardar perfil</button></div>`;modal.hidden=false;document.getElementById('saveProfile').onclick=saveProfile}
async function saveProfile(){const specialties=[...modalBody.querySelectorAll('.check input:checked')].map(x=>x.value);const profile={full_name:document.getElementById('pf-name').value,alias:document.getElementById('pf-alias').value,email:document.getElementById('pf-email').value,company:document.getElementById('pf-company').value,province:document.getElementById('pf-prov').value,city:document.getElementById('pf-city').value,bio:document.getElementById('pf-bio').value,specialties};try{await privateCall('update_profile',{profile});modal.hidden=true;showToast('Perfil actualizado');await load()}catch(e){showToast(e.message)}}
function openSecurity(){const acts=data.activity||[];modalBody.innerHTML=`<h2>Seguridad de acceso</h2><p class="muted">Tu QR y tu código de referido nunca sirven para iniciar sesión. El acceso se protege con la sesión del dispositivo y tu autenticación.</p><div class="security"><div class="securityItem"><b>Face ID / huella / PIN del dispositivo</b><p>Puedes registrar una passkey si está habilitada para este proyecto y tu navegador la admite.</p><div class="actions"><button class="btn primary" id="passkey">Activar passkey</button></div></div><div class="securityItem"><b>Otras sesiones</b><p>Si pierdes un dispositivo, puedes cerrar el resto de sesiones asociadas a tu cuenta.</p><div class="actions"><button class="btn" id="signoutOthers">Cerrar otras sesiones</button></div></div><div class="securityItem"><b>Actividad reciente</b>${acts.length?acts.slice(0,6).map(a=>`<p>${new Date(a.created_at).toLocaleString('es-ES')} · ${esc(a.event_type)}${a.device_label?` · ${esc(a.device_label)}`:''}</p>`).join(''):'<p>Sin actividad anterior.</p>'}</div><div class="securityItem"><b>Salir de este dispositivo</b><div class="actions"><button class="btn danger" id="logout">Cerrar sesión</button></div></div></div>`;modal.hidden=false;document.getElementById('passkey').onclick=registerPasskey;document.getElementById('signoutOthers').onclick=signoutOthers;document.getElementById('logout').onclick=logout}
async function registerPasskey(){try{const{data:pk,error}=await supabase.auth.registerPasskey();if(error)throw error;await privateCall('activity',{event_type:'passkey_registered',device_label:deviceLabel()});showToast(`Passkey activada${pk?.friendly_name?`: ${pk.friendly_name}`:''}`);modal.hidden=true;await load()}catch(e){showToast(/passkey_disabled/i.test(e.message)?'Las passkeys aún no están habilitadas en el proyecto de autenticación.':e.message)}}
async function signoutOthers(){const{error}=await supabase.auth.signOut({scope:'others'});if(error)showToast(error.message);else{showToast('Otras sesiones cerradas');await privateCall('activity',{event_type:'other_sessions_revoked',device_label:deviceLabel()})}}
async function logout(){await supabase.auth.signOut({scope:'local'});modal.hidden=true;data=null;renderAuth()}
document.querySelectorAll('[data-close-modal]').forEach(x=>x.onclick=()=>modal.hidden=true);

const{data:initial}=await supabase.auth.getSession();if(initial.session)load();else renderAuth();
