(()=>{'use strict';
const SUPA='https://kgcuqxzpxykqszdeonte.supabase.co/functions/v1',INTAKE=SUPA+'/submit-intake',CONTENT=SUPA+'/public-content',OFFER=SUPA+'/submit-offer',WA='34633671657',PANEL='https://panel.fibaroteleco.com/login';
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];

const intro=$('#intro'),count=$('#introCount');let n=0;const timer=setInterval(()=>{n=Math.min(100,n+8);if(count)count.textContent=String(n).padStart(3,'0');if(n>=100)clearInterval(timer)},90);setTimeout(()=>intro?.classList.add('done'),1900);intro?.addEventListener('click',()=>intro.classList.add('done'));

const menu=$('#menuBtn'),mobile=$('#mobileNav');menu?.addEventListener('click',()=>mobile?.classList.toggle('open'));$$('#mobileNav a').forEach(a=>a.addEventListener('click',()=>mobile?.classList.remove('open')));

fetch('/alicia.b64',{cache:'force-cache'}).then(r=>{if(!r.ok)throw new Error('photo');return r.text()}).then(s=>{$$('.alicia').forEach(i=>{i.src='data:image/webp;base64,'+s.trim()})}).catch(()=>{});

const path=location.pathname.replace(/^\/+|\/+$/g,'');
if(path==='area-cliente'){location.replace(PANEL);return}
if(path==='privacidad'||path==='aviso-legal'){
 const m=$('#main');
 const privacy=`<article class="legal"><a class="backlink" href="/">← FÍBARO</a><h1>Política de privacidad</h1><h2>Responsable</h2><p><strong>MEJIAS BUSINESS S.L.</strong><br>CIF: B75334714<br>Establecimiento FÍBARO: C/ Infanta Beatriz nº13, 11540 Sanlúcar de Barrameda (Cádiz).<br>Teléfono y WhatsApp: 633 671 657.</p><h2>Finalidad</h2><p>Tratamos los datos que facilites para atender solicitudes, preparar comparaciones u ofertas, gestionar una contratación cuando la solicites, realizar seguimiento y conservar el contexto comercial necesario para atenderte correctamente.</p><h2>Base jurídica</h2><p>La base jurídica es la aplicación de medidas precontractuales solicitadas por el interesado y, cuando corresponda, el consentimiento.</p><h2>Destinatarios</h2><p>Cuando solicites una contratación, los datos podrán comunicarse al operador, comercializadora o proveedor necesario para tramitarla, así como a proveedores tecnológicos imprescindibles.</p><h2>Derechos</h2><p>Puedes solicitar acceso, rectificación, supresión, oposición, limitación o portabilidad cuando resulte aplicable y reclamar ante la Agencia Española de Protección de Datos.</p></article>`;
 const legal=`<article class="legal"><a class="backlink" href="/">← FÍBARO</a><h1>Aviso legal</h1><h2>Titular</h2><p><strong>MEJIAS BUSINESS S.L.</strong><br>CIF: B75334714<br>Establecimiento FÍBARO: C/ Infanta Beatriz nº13, 11540 Sanlúcar de Barrameda (Cádiz).</p><h2>Actividad</h2><p>FÍBARO Telecomunicaciones es una denominación comercial utilizada para la actividad de asesoramiento y comercialización de telecomunicaciones y energía. FÍBARO no es un operador de red ni una comercializadora de energía.</p><h2>Ofertas y contratación</h2><p>Las ofertas, coberturas, plazos y condiciones están sujetas a elegibilidad, disponibilidad, vigencia y condiciones del proveedor correspondiente. Ningún alta o cambio se tramita sin autorización del cliente.</p><h2>Instalaciones y soluciones especiales</h2><p>La posibilidad de adelantar instalaciones depende de la liberación de la orden, la operadora y la viabilidad técnica. Las soluciones de conectividad especial pueden requerir equipamiento, instalación y costes diferentes de una conexión estándar.</p></article>`;
 if(m)m.innerHTML=path==='privacidad'?privacy:legal;$$('header,.ticker').forEach(x=>x.style.display='none');document.title=(path==='privacidad'?'Privacidad':'Aviso legal')+' | FÍBARO';return;
}

const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.08});function observe(){$$('.reveal').forEach(x=>io.observe(x))}observe();

const problems={
 wifi:['ANTES DE CAMBIAR DE OPERADOR, HAY QUE SABER QUÉ ESTÁ FALLANDO.','Un mal wifi puede venir de la línea, del router, de la instalación o de la cobertura dentro de casa. Cambiar a ciegas puede dejarte exactamente igual.',[['Diagnóstico','Separar línea, router, instalación y cobertura interior.'],['Criterio','Ver si conviene ajustar, mejorar o cambiar.'],['Ejecución','Aplicar la solución que sí tiene sentido.']]],
 precio:['EL PRECIO DEL PRIMER MES NO ES EL PRECIO REAL.','Revisamos líneas, extras, permanencias y lo que realmente utilizas. Ahorrar también puede significar simplificar en vez de perseguir una promoción.',[['Inventario','Qué tienes y qué pagas de verdad.'],['Comparación','Qué alternativas aportan una mejora real.'],['Decisión','Cambiar solo cuando compensa.']]],
 cambio:['CAMBIAR ES FÁCIL. HACERLO SIN SORPRESAS YA ES OTRA COSA.','Cobertura, portabilidad, instalación y tiempos importan tanto como la tarifa. El cambio necesita un responsable, no solo un pedido.',[['Cobertura','Validamos el escenario antes de mover nada.'],['Plan','Preparamos el paso a paso.'],['Seguimiento','El caso continúa hasta quedar encarrilado.']]],
 alta:['UNA BUENA INSTALACIÓN EMPIEZA ANTES DE QUE LLEGUE EL TÉCNICO.','En Zona FÍBARO, si la orden ya está liberada y es viable, muchas instalaciones pueden adelantarse respecto a la cita estándar gracias a nuestra capacidad operativa.',[['Validar','Dirección, cobertura y necesidad.'],['Coordinar','Ordenar el alta y la intervención.'],['Acelerar','Aprovechar el margen operativo cuando existe.']]],
 empresa:['UNA EMPRESA NO NECESITA UNA TARIFA SUELTA. NECESITA CONTROL.','Sedes, líneas, conectividad y energía necesitan contexto y prioridades. Primero ordenamos el mapa y después tocamos lo que merece la pena.',[['Mapa','Servicios y puntos críticos.'],['Prioridad','Qué resolver primero.'],['Continuidad','Un mismo contexto para todo el caso.']]],
 dificil:['SI LA VÍA CONVENCIONAL NO LLEGA, EL CASO NO TERMINA AHÍ.','Estudiamos la ubicación y la necesidad para plantear una alternativa de conectividad viable, explicando de antemano la instalación y el equipamiento que pueda requerir.',[['Estudio','Ubicación, uso y limitaciones reales.'],['Viabilidad','Qué tecnología o solución tiene sentido.'],['Propuesta','Una salida concreta, no una respuesta automática.']]]
};
function renderProblem(k){const d=problems[k];$('#problemTitle').textContent=d[0];$('#problemText').textContent=d[1];$('#problemSteps').innerHTML=d[2].map(x=>`<div><b>${x[0]}</b><span>${x[1]}</span></div>`).join('');$$('.problem').forEach(b=>b.classList.toggle('active',b.dataset.problem===k))}$$('.problem').forEach(b=>b.onclick=()=>renderProblem(b.dataset.problem));renderProblem('wifi');

function attribution(fd){const q=new URLSearchParams(location.search);fd.set('utm_source',q.get('utm_source')||q.get('src')||'directo');fd.set('utm_medium',q.get('utm_medium')||'');fd.set('utm_campaign',q.get('utm_campaign')||'');fd.set('utm_content',q.get('utm_content')||'');fd.set('landing_path',location.pathname);fd.set('referrer',document.referrer||'');try{let id=localStorage.getItem('fibaro_anon');if(!id){id=crypto.randomUUID();localStorage.setItem('fibaro_anon',id)}fd.set('anonymous_id',id)}catch{}}
async function send(url,fd,timeout=16000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{method:'POST',body:fd,signal:c.signal});const j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.error||'No se ha podido completar la solicitud.');return j}finally{clearTimeout(t)}}
function wa(text){window.open('https://wa.me/'+WA+'?text='+encodeURIComponent(text),'_blank','noopener')}

async function loadPublic(){try{const r=await fetch(CONTENT,{headers:{Accept:'application/json'},cache:'no-store'});const j=await r.json();if(!r.ok||!j.ok)throw new Error();renderOffers(j.offers||[]);renderInstagram(j.instagram||[])}catch{renderOffers([]);renderInstagram([])}}
function safe(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderOffers(a){const g=$('#offersGrid');if(!a.length){g.innerHTML='<div class="emptyState">Ahora mismo no hay ofertas destacadas publicadas. Puedes enviarnos tu caso y revisaremos la opción adecuada.</div>';return}g.innerHTML=a.slice(0,6).map(o=>`<article class="offerCard reveal">${o.image_url?`<img src="${safe(o.image_url)}" alt="">`:''}<div class="offerBody"><small>Oferta destacada</small><h3>${safe(o.title)}</h3>${o.caption?`<p class="caption">${safe(o.caption)}</p>`:''}<p>${safe(o.description)}</p><button class="primary" data-offer="${safe(o.id)}" data-title="${safe(o.title)}" data-copy="${safe(o.caption||o.description)}">${safe(o.cta_label||'Solicitar con prioridad')}</button></div></article>`).join('');$$('[data-offer]',g).forEach(b=>b.onclick=()=>openOffer(b.dataset.offer,b.dataset.title,b.dataset.copy));observe()}
function renderInstagram(a){const g=$('#instagramGrid');if(!a.length){g.innerHTML='<div class="emptyState" style="color:#5f6d7b;border-color:#b9c5d0">Alicia todavía no ha anclado publicaciones. Puedes visitar el perfil de FÍBARO directamente.</div>';return}g.innerHTML=a.slice(0,6).map(p=>`<article class="instagramCard reveal">${p.image_url?`<img src="${safe(p.image_url)}" alt="">`:''}<div><p>${safe(p.caption)}</p><a href="${safe(p.post_url)}" target="_blank" rel="noopener">Abrir en Instagram ↗</a></div></article>`).join('');observe()}
loadPublic();

const modal=$('#offerModal'),offerForm=$('#offerForm');function openOffer(id,title,copy){$('#featuredOfferId').value=id;$('#offerModalTitle').textContent=title||'Oferta destacada';$('#offerModalCopy').textContent=copy||'';$('#offerStatus').textContent='';modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';offerForm.elements.nombre.focus()}function closeOffer(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}$$('[data-close-offer]').forEach(x=>x.onclick=closeOffer);addEventListener('keydown',e=>{if(e.key==='Escape'){closeOffer();mobile?.classList.remove('open')}});
offerForm.onsubmit=async e=>{e.preventDefault();const fd=new FormData(offerForm),status=$('#offerStatus'),btn=$('#offerSend');if(!fd.get('consent')){status.textContent='Debes aceptar la política de privacidad.';return}fd.set('consent','yes');fd.set('featured_offer_id',$('#featuredOfferId').value);attribution(fd);btn.disabled=true;btn.textContent='Enviando…';status.textContent='';try{await send(OFFER,fd);status.textContent='Solicitud enviada como urgente. Alicia la verá con prioridad.';offerForm.reset();setTimeout(closeOffer,1300)}catch(err){status.textContent=err.message||'No se ha podido enviar. Abriendo WhatsApp…';wa('Hola FÍBARO, quiero solicitar la oferta destacada: '+$('#offerModalTitle').textContent)}finally{btn.disabled=false;btn.textContent='Solicitar con prioridad'}};

const leadForm=$('#leadForm');leadForm.onsubmit=async e=>{e.preventDefault();const fd=new FormData(leadForm),status=$('#leadStatus'),btn=$('#leadSend');if(!fd.get('consent')){status.textContent='Debes aceptar la política de privacidad.';return}fd.set('consent','yes');fd.set('intent','web');fd.set('contact_preference','whatsapp');attribution(fd);btn.disabled=true;btn.textContent='Enviando…';status.textContent='';try{const r=await send(INTAKE,fd);status.textContent='Solicitud enviada. Referencia '+(r.reference||'')+'.';leadForm.reset()}catch(err){status.textContent=err.message||'No se ha podido enviar. Abriendo WhatsApp…';wa('Hola FÍBARO, quiero que reviséis mi caso.')}finally{btn.disabled=false;btn.textContent='Enviar a FÍBARO'}};

$$('[data-open-general]').forEach(b=>b.onclick=()=>{$('#contacto').scrollIntoView({behavior:'smooth'});setTimeout(()=>leadForm.elements.nombre.focus(),400)});
})();
