(()=>{'use strict';
const PUBLIC='https://kgcuqxzpxykqszdeonte.supabase.co/functions/v1/public-content';
const INTAKE='https://kgcuqxzpxykqszdeonte.supabase.co/functions/v1/submit-intake';
const KEY='sb_publishable_I5X2IBZZkmFyDDez_Kf4aA_hNyLkzay';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const track=(name,data={})=>window.FibaroAnalytics?.track?.(name,data);
const esc=(value='')=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selectedNeed='';let step=1;let lastFocus=null;

function intro(){const el=$('#intro');if(!el)return;let seen=false;try{seen=sessionStorage.getItem('fibaro_intro_seen')==='1';sessionStorage.setItem('fibaro_intro_seen','1')}catch{};if(seen||matchMedia('(prefers-reduced-motion: reduce)').matches){el.remove();return}setTimeout(()=>el.classList.add('done'),520);setTimeout(()=>el.remove(),820)}
function menu(){const btn=$('#menuBtn'),nav=$('#mobileNav');if(!btn||!nav)return;btn.addEventListener('click',()=>{const open=nav.classList.toggle('open');btn.setAttribute('aria-expanded',String(open))});nav.addEventListener('click',()=>{nav.classList.remove('open');btn.setAttribute('aria-expanded','false')})}
function businessState(){const el=$('#openState');if(!el)return;const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Madrid',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).reduce((a,p)=>(a[p.type]=p.value,a),{});const weekend=['Sat','Sun'].includes(parts.weekday),mins=Number(parts.hour)*60+Number(parts.minute),open=weekend?mins>=600&&mins<900:mins>=570&&mins<1290;el.className='openState '+(open?'open':'closed');el.textContent=open?'● Estamos atendiendo ahora':'Ahora estamos cerrados · puedes dejarnos tu consulta'}
function experiment(){let variant='A';try{variant=localStorage.getItem('fibaro_exp_home_cta')||((crypto.getRandomValues(new Uint8Array(1))[0]%2)?'B':'A');localStorage.setItem('fibaro_exp_home_cta',variant)}catch{};document.documentElement.dataset.homeCtaVariant=variant;if(variant==='B')$$('[data-start-wizard]').forEach((b,i)=>{if(i===0)b.textContent='Ver qué me conviene'});track('experiment_exposure',{experiment:'home_cta_2026_10',variant})}
const needs={
 fiber:{label:'Fibra y móvil',title:'Compara con cobertura y condiciones reales',copy:'Te ayudamos a valorar velocidad, líneas, precio final y permanencia antes de tramitar nada.',wa:'Hola Alicia, quiero revisar fibra o móvil.'},
 business:{label:'Empresas',title:'Ordena líneas, sedes y prioridades',copy:'Revisamos qué necesita el negocio y coordinamos el cambio para reducir interrupciones y llamadas repetidas.',wa:'Hola Alicia, quiero revisar la conectividad de mi empresa.'},
 energy:{label:'Energía',title:'Comprueba primero si cambiar compensa',copy:'Envíanos tu factura y revisamos consumo y condiciones. Si no hay una mejora clara, te lo decimos.',wa:'Hola Alicia, quiero revisar mi factura de luz.'},
 connectivity:{label:'Conectividad especial',title:'Que no llegue la fibra no cierra el caso',copy:'Estudiamos la ubicación y las alternativas técnicas viables, con equipamiento y costes explicados antes.',wa:'Hola Alicia, necesito conexión en una ubicación donde no llega la fibra.'}
};
function selectNeed(key,open=false){if(!needs[key])return;selectedNeed=key;$$('[data-need]').forEach(b=>b.classList.toggle('selected',b.dataset.need===key));const n=needs[key],result=$('#needResult');$('#needLabel').textContent=n.label;$('#needTitle').textContent=n.title;$('#needCopy').textContent=n.copy;$('#needWhatsApp').href=`https://wa.me/34633671657?text=${encodeURIComponent(n.wa)}`;result.hidden=false;result.focus({preventScroll:true});const radio=$(`#leadForm input[name="need"][value="${key}"]`);if(radio)radio.checked=true;track('need_selected',{interest:key});if(open)openWizard()}
function bindNeeds(){$$('[data-need]').forEach(b=>b.addEventListener('click',()=>selectNeed(b.dataset.need)));$$('[data-start-wizard]').forEach(b=>b.addEventListener('click',openWizard))}
function isZone(cp){if(!/^\d{5}$/.test(cp))return null;const known=new Set(['11540','11539','11520','11550','11500','11510','11591','11593']);return known.has(cp)||(Number(cp)>=11401&&Number(cp)<=11409)}
function zone(){$('#zoneForm')?.addEventListener('submit',e=>{e.preventDefault();const cp=$('#zonePostal').value.trim(),status=$('#zoneStatus'),inside=isZone(cp);if(inside===null){status.textContent='Escribe un código postal español de 5 cifras.';status.className='zoneStatus error';return}status.className='zoneStatus';status.innerHTML=inside?'<strong>Sí, estás en Zona FÍBARO.</strong> Podemos comprobar la disponibilidad técnica local.':'<strong>Te atendemos igualmente.</strong> La gestión comercial y el seguimiento están disponibles en toda España.';const wizardCp=$('#leadForm [name="postal_code"]');if(wizardCp)wizardCp.value=cp;track('zone_checked',{technical_zone:inside?'yes':'no'});})}
function offerCard(o){return `<article class="offerCard"><small>${esc(o.caption||'Opción destacada')}</small><h3>${esc(o.title)}</h3><p>${esc(o.description)}</p><button class="button primary offerCta" data-offer-id="${esc(o.id)}" data-offer-service="${esc(o.service_type||'fiber')}">${esc(o.cta_label||'Quiero información')}</button></article>`}
async function content(){const grid=$('#offersGrid');if(!grid)return;try{const r=await fetch(PUBLIC,{headers:{apikey:KEY}}),j=await r.json();if(!r.ok||!j.ok)throw new Error('Contenido no disponible');const offers=(j.offers||[]).slice(0,3);grid.innerHTML=offers.length?offers.map(offerCard).join(''):'<p>Alicia puede revisar contigo las opciones disponibles ahora.</p>';$$('[data-offer-id]',grid).forEach(b=>b.addEventListener('click',()=>{const raw=b.dataset.offerService||'fiber',key=raw==='energy'?'energy':raw==='company'?'business':'fiber';selectNeed(key);track('offer_clicked',{offer_id:b.dataset.offerId});openWizard()}));const campaign=(j.campaigns||[])[0];if(campaign)renderCampaign(campaign)}catch{grid.innerHTML='<p>No hemos podido cargar la selección ahora. Puedes pedir a Alicia que revise tu caso.</p>'}}
function renderCampaign(c){const slot=$('#campaignSlot');if(!slot)return;slot.innerHTML=`<div class="campaignInner"><div><span class="eyebrow dark">Campaña vigente</span><h2>${esc(c.name)}</h2><p>${esc(c.description||'Consulta condiciones y disponibilidad.')}</p></div><button class="button dark" data-campaign-start>Quiero información</button></div>`;slot.hidden=false;$('[data-campaign-start]',slot).addEventListener('click',()=>{selectedNeed='fiber';track('campaign_viewed',{campaign:esc(c.slug)});openWizard()})}
function setStep(next){step=Math.max(1,Math.min(3,next));$$('.wizardStep').forEach(s=>s.hidden=Number(s.dataset.step)!==step);$('#wizardProgress').textContent=`Paso ${step} de 3`;$('#wizardBar').style.width=`${step*33.333}%`;$('#wizardBack').hidden=step===1;$('#wizardNext').hidden=step===3;$('#leadSend').hidden=step!==3;$('.wizardStep:not([hidden]) input, .wizardStep:not([hidden]) textarea')?.focus();track('funnel_step',{step:String(step),interest:selectedNeed||'unknown'})}
function validateStep(){const section=$(`.wizardStep[data-step="${step}"]`);const required=$$('[required]',section);for(const field of required){if((field.type==='radio'&&!$(`input[name="${field.name}"]:checked`,section))||(field.type==='checkbox'&&!field.checked)||(!['radio','checkbox'].includes(field.type)&&!field.value.trim())){field.focus();$('#leadStatus').textContent='Completa este paso para continuar.';$('#leadStatus').className='status error';return false}}if(step===3){const phone=$('[name="telefono"]').value.replace(/\D/g,'').replace(/^34(?=\d{9}$)/,'');if(phone.length!==9){$('[name="telefono"]').focus();$('#leadStatus').textContent='Indica un teléfono español válido de 9 cifras.';$('#leadStatus').className='status error';return false}}$('#leadStatus').textContent='';return true}
function openWizard(){lastFocus=document.activeElement;const modal=$('#leadWizard');modal.hidden=false;document.body.style.overflow='hidden';if(selectedNeed){const radio=$(`input[name="need"][value="${selectedNeed}"]`);if(radio)radio.checked=true}setStep(selectedNeed?2:1);track('funnel_started',{interest:selectedNeed||'unknown'});$('.wizardClose').focus()}
function closeWizard(){const modal=$('#leadWizard');modal.hidden=true;document.body.style.overflow='';lastFocus?.focus?.()}
function wizard(){const modal=$('#leadWizard');if(!modal)return;$$('[data-close-wizard]').forEach(b=>b.addEventListener('click',closeWizard));$('#wizardNext').addEventListener('click',()=>{if(validateStep())setStep(step+1)});$('#wizardBack').addEventListener('click',()=>setStep(step-1));modal.addEventListener('keydown',e=>{if(e.key==='Escape')closeWizard();if(e.key==='Tab'){const f=$$('button:not([hidden]),a[href],input:not([type="hidden"]),textarea',modal).filter(x=>!x.closest('[hidden]'));if(!f.length)return;const first=f[0],last=f.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});$('#leadForm').addEventListener('submit',submitLead)}
async function submitLead(e){e.preventDefault();if(!validateStep())return;const form=e.currentTarget,btn=$('#leadSend'),status=$('#leadStatus'),data=new FormData(form),need=data.get('need'),service=need==='energy'?'energy':need==='fiber'?'fiber':'callback';data.set('servicio',service);data.set('intent','web');data.set('funnel_detail','block10_need_selector');data.set('funnel_objective',String(data.get('objective')||'help'));data.set('funnel_context',JSON.stringify({interest:need,entry:'block10_wizard',technical_zone:isZone(String(data.get('postal_code')||'')),experiment:document.documentElement.dataset.homeCtaVariant||'A'}));data.set('privacy_notice_version','2026-09-14-v1');window.FibaroAnalytics?.enrichFormData?.(data);btn.disabled=true;status.className='status';status.textContent='Enviando…';try{const r=await fetch(INTAKE,{method:'POST',headers:{apikey:KEY},body:data}),j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.error||'No se pudo enviar la solicitud.');track('funnel_completed',{interest:String(need)});$('.wizardCard').innerHTML=`<div class="successPanel"><b>✓</b><h2>Solicitud recibida</h2><p>Alicia revisará tu caso y te contactará por el canal elegido.</p>${j.reference?`<p class="reference">${esc(j.reference)}</p><p>Guarda esta referencia por si quieres identificar tu solicitud.</p>`:''}<a class="button primary" href="https://wa.me/34633671657?text=${encodeURIComponent('Hola Alicia. He enviado una solicitud'+(j.reference?' con referencia '+j.reference:'')+'.')}" target="_blank" rel="noopener">Abrir WhatsApp</a></div>`}catch(err){status.textContent=err.message;status.className='status error';btn.disabled=false}}
function personalize(){const q=new URLSearchParams(location.search),interest=(q.get('interest')||q.get('utm_content')||'').toLowerCase();const map={empresa:'business',business:'business',energia:'energy',luz:'energy',fibra:'fiber',movil:'fiber',cobertura:'connectivity'};if(map[interest]){const key=map[interest],hero=$('.heroLead');hero.textContent=needs[key].copy;selectedNeed=key}}
function smooth(){document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a)return;const target=$(a.getAttribute('href'));if(!target)return;e.preventDefault();target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})})}
intro();menu();businessState();experiment();personalize();bindNeeds();zone();wizard();smooth();content();
})();
