(()=>{'use strict';
const SUPA='https://kgcuqxzpxykqszdeonte.supabase.co/functions/v1',INTAKE=SUPA+'/submit-intake',CONTENT=SUPA+'/public-content',OFFER=SUPA+'/submit-offer',WA='34633671657',PANEL='https://panel.fibaroteleco.com/login',NOTICE='2026-09-14-v1';
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const qs=new URLSearchParams(location.search);
const routePath=location.pathname.replace(/^\/+|\/+$/g,'');
const SUPPORT_HOLIDAYS=new Set(['2026-01-01','2026-01-06','2026-02-28','2026-04-02','2026-04-03','2026-05-01','2026-06-08','2026-08-15','2026-10-12','2026-10-19','2026-11-02','2026-12-07','2026-12-08','2026-12-25','2027-01-01','2027-01-06','2027-03-01','2027-03-25','2027-03-26','2027-05-01','2027-08-16','2027-10-12','2027-11-01','2027-12-06','2027-12-08','2027-12-25']);
const MADRID_PARTS=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});
let sessionId='';try{sessionId=sessionStorage.getItem('fibaro_session')||crypto.randomUUID();sessionStorage.setItem('fibaro_session',sessionId)}catch{try{sessionId='fb-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)}catch{}}
function campaignAttribution(){const explicit=qs.get('utm_campaign');if(explicit)return explicit;return routePath==='regalo'&&(qs.get('utm_source')||qs.get('src'))?'navidad2026':''}
function attribution(fd){if(sessionId)fd.set('anonymous_id',sessionId);fd.set('utm_source',qs.get('utm_source')||qs.get('src')||'directo');fd.set('utm_medium',qs.get('utm_medium')||'');fd.set('utm_campaign',campaignAttribution());fd.set('utm_content',qs.get('utm_content')||'');fd.set('landing_path',location.pathname);fd.set('referrer',document.referrer||'');fd.set('privacy_notice',NOTICE)}
async function send(url,fd,timeout=16000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{method:'POST',body:fd,signal:c.signal});const j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.error||'No se ha podido completar la solicitud.');return j}finally{clearTimeout(t)}}
function track(eventName,payload={}){try{const fd=new FormData();fd.set('mode','event');fd.set('event_name',eventName);fd.set('payload',JSON.stringify(payload));attribution(fd);fetch(INTAKE,{method:'POST',body:fd,keepalive:true}).catch(()=>{})}catch{}}
function supportState(date=new Date()){const values={};for(const part of MADRID_PARTS.formatToParts(date))if(part.type!=='literal')values[part.type]=part.value;const iso=`${values.year}-${values.month}-${values.day}`,weekend=values.weekday==='Sat'||values.weekday==='Sun',special=weekend||SUPPORT_HOLIDAYS.has(iso),minute=Number(values.hour)*60+Number(values.minute),open=special?10*60:9*60+30,close=special?15*60:21*60+30;return{special,inHours:minute>=open&&minute<close}}
function successMessage(reference){const state=supportState(),ref=reference?` Referencia: ${reference}`:'';if(state.inHours&&!state.special)return`¡Recibido! Una persona del equipo te escribe por WhatsApp en unos minutos.${ref}`;if(state.inHours)return`¡Gracias! Hoy te atendemos de 10:00 a 15:00. Puede que tardemos un poquito más, pero te contestamos hoy 🙂${ref}`;return`¡Gracias! Hemos recibido tu mensaje. Te atiende una persona de lunes a viernes de 9:30 a 21:30, y sábados, domingos y festivos de 10:00 a 15:00. Te escribimos en cuanto abramos 🙂${ref}`}
track('page_view',{page:location.pathname,title:document.title});
const intro=$('#intro'),count=$('#introCount');let n=0;if(intro){const timer=setInterval(()=>{n=Math.min(100,n+8);if(count)count.textContent=String(n).padStart(3,'0');if(n>=100)clearInterval(timer)},90);setTimeout(()=>intro.classList.add('done'),1900);intro.addEventListener('click',()=>intro.classList.add('done'))}
const menu=$('#menuBtn'),mobile=$('#mobileNav');menu?.addEventListener('click',()=>mobile?.classList.toggle('open'));$$('#mobileNav a').forEach(a=>a.addEventListener('click',()=>mobile?.classList.remove('open')));
$$('.alicia').forEach(i=>{i.src='/alicia.webp?v=20260913-2';i.loading='lazy';i.decoding='async'});
document.addEventListener('click',event=>{const target=event.target instanceof Element?event.target:null,a=target?.closest('a[href*="wa.me"]');if(a)track('whatsapp_clicked',{page:location.pathname,cta_position:a.dataset.track||a.closest('section')?.id||'global'});const tracked=target?.closest('[data-track-cta]');if(tracked)track('funnel_started',{page:location.pathname,cta_position:tracked.getAttribute('data-track-cta')})});
function wa(text){track('whatsapp_clicked',{page:location.pathname,cta_position:'fallback'});window.open('https://wa.me/'+WA+'?text='+encodeURIComponent(text),'_blank','noopener')}
if(routePath==='area-cliente'){location.replace(PANEL);return}
const io='IntersectionObserver'in window?new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.08}):null;function observe(){if(io)$$('.reveal').forEach(x=>io.observe(x));else $$('.reveal').forEach(x=>x.classList.add('in'))}observe();
const problems={wifi:['ANTES DE CAMBIAR DE OPERADOR, HAY QUE SABER QUÉ ESTÁ FALLANDO.','Un mal wifi puede venir de la línea, del router, de la instalación o de la cobertura dentro de casa. Cambiar a ciegas puede dejarte exactamente igual.',[['Diagnóstico','Separar línea, router, instalación y cobertura interior.'],['Criterio','Ver si conviene ajustar, mejorar o cambiar.'],['Ejecución','Aplicar la solución que sí tiene sentido.']]],precio:['EL PRECIO DEL PRIMER MES NO ES EL PRECIO REAL.','Revisamos líneas, extras, permanencias y lo que realmente utilizas. Ahorrar también puede significar simplificar en vez de perseguir una promoción.',[['Inventario','Qué tienes y qué pagas de verdad.'],['Comparación','Qué alternativas aportan una mejora real.'],['Decisión','Cambiar solo cuando compensa.']]],cambio:['CAMBIAR ES FÁCIL. HACERLO SIN SORPRESAS YA ES OTRA COSA.','Cobertura, portabilidad, instalación y tiempos importan tanto como la tarifa. El cambio necesita un responsable, no solo un pedido.',[['Cobertura','Validamos el escenario antes de mover nada.'],['Plan','Preparamos el paso a paso.'],['Seguimiento','El caso continúa hasta quedar encarrilado.']]],alta:['UNA BUENA INSTALACIÓN EMPIEZA ANTES DE QUE LLEGUE EL TÉCNICO.','En Zona FÍBARO, si la orden ya está liberada y es viable, muchas instalaciones pueden adelantarse respecto a la cita estándar gracias a nuestra capacidad operativa.',[['Validar','Dirección, cobertura y necesidad.'],['Coordinar','Ordenar el alta y la intervención.'],['Acelerar','Aprovechar el margen operativo cuando existe.']]],empresa:['UNA EMPRESA NO NECESITA UNA TARIFA SUELTA. NECESITA CONTROL.','Sedes, líneas, conectividad y energía necesitan contexto y prioridades. Primero ordenamos el mapa y después tocamos lo que merece la pena.',[['Mapa','Servicios y puntos críticos.'],['Prioridad','Qué resolver primero.'],['Continuidad','Un mismo contexto para todo el caso.']]],dificil:['SI LA VÍA CONVENCIONAL NO LLEGA, EL CASO NO TERMINA AHÍ.','Estudiamos la ubicación y la necesidad para plantear una alternativa de conectividad viable, explicando de antemano la instalación y el equipamiento que pueda requerir.',[['Estudio','Ubicación, uso y limitaciones reales.'],['Viabilidad','Qué tecnología o solución tiene sentido.'],['Propuesta','Una salida concreta, no una respuesta automática.']]]};
function renderProblem(k){const title=$('#problemTitle'),body=$('#problemText'),steps=$('#problemSteps');if(!title||!body||!steps)return;const d=problems[k];title.textContent=d[0];body.textContent=d[1];steps.innerHTML=d[2].map(x=>`<div><b>${x[0]}</b><span>${x[1]}</span></div>`).join('');$$('.problem').forEach(b=>b.classList.toggle('active',b.dataset.problem===k))}$$('.problem').forEach(b=>b.onclick=()=>{track('funnel_step',{step:'problem',value:b.dataset.problem});renderProblem(b.dataset.problem)});if($('#problemTitle'))renderProblem('wifi');
async function loadPublic(){if(!$('#offersGrid')&&!$('#instagramGrid'))return;try{const r=await fetch(CONTENT,{headers:{Accept:'application/json'},cache:'no-store'});const j=await r.json();if(!r.ok||!j.ok)throw new Error();renderOffers(j.offers||[]);renderInstagram(j.instagram||[])}catch{renderOffers([]);renderInstagram([])}}
function safe(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function safeUrl(v){try{const u=new URL(String(v||''),location.origin);return u.protocol==='https:'||u.protocol==='http:'?u.href:''}catch{return ''}}
function renderOffers(a){const g=$('#offersGrid');if(!g)return;if(!a.length){g.innerHTML='<div class="emptyState">Ahora mismo no hay ofertas destacadas publicadas. Puedes enviarnos tu caso y revisaremos la opción adecuada.</div>';return}g.innerHTML=a.slice(0,6).map(o=>{const image=safeUrl(o.image_url);return `<article class="offerCard reveal">${image?`<img src="${safe(image)}" alt="" loading="lazy">`:''}<div class="offerBody"><small>Oferta destacada</small><h3>${safe(o.title)}</h3>${o.caption?`<p class="caption">${safe(o.caption)}</p>`:''}<p>${safe(o.description)}</p><button class="primary" data-offer="${safe(o.id)}" data-title="${safe(o.title)}" data-copy="${safe(o.caption||o.description)}">${safe(o.cta_label||'Solicitar con prioridad')}</button></div></article>`}).join('');$$('[data-offer]',g).forEach(b=>b.onclick=()=>{track('funnel_started',{type:'featured_offer',offer_id:b.dataset.offer});openOffer(b.dataset.offer,b.dataset.title,b.dataset.copy)});observe()}
function renderInstagram(a){const g=$('#instagramGrid');if(!g)return;if(!a.length){g.innerHTML='<div class="emptyState" style="color:#5f6d7b;border-color:#b9c5d0">Puedes ver las últimas publicaciones directamente en el Instagram de FÍBARO.</div>';return}g.innerHTML=a.slice(0,6).map(p=>{const image=safeUrl(p.image_url),post=safeUrl(p.post_url);return `<article class="instagramCard reveal">${image?`<img src="${safe(image)}" alt="" loading="lazy">`:''}<div><p>${safe(p.caption)}</p>${post?`<a href="${safe(post)}" target="_blank" rel="noopener">Abrir en Instagram ↗</a>`:''}</div></article>`}).join('');observe()}loadPublic();
const modal=$('#offerModal'),offerForm=$('#offerForm');function openOffer(id,title,copy){if(!modal||!offerForm)return;$('#featuredOfferId').value=id;$('#offerModalTitle').textContent=title||'Oferta destacada';$('#offerModalCopy').textContent=copy||'';$('#offerStatus').textContent='';modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';offerForm.elements.nombre.focus()}function closeOffer(){if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}$$('[data-close-offer]').forEach(x=>x.onclick=closeOffer);addEventListener('keydown',e=>{if(e.key==='Escape'){closeOffer();mobile?.classList.remove('open')}});
if(offerForm)offerForm.onsubmit=async e=>{e.preventDefault();const fd=new FormData(offerForm),status=$('#offerStatus'),btn=$('#offerSend');fd.set('featured_offer_id',$('#featuredOfferId').value);attribution(fd);btn.disabled=true;btn.textContent='Enviando…';status.textContent='';try{await send(OFFER,fd);status.textContent='Solicitud enviada como urgente. Alicia la verá con prioridad.';track('funnel_completed',{type:'featured_offer'});offerForm.reset();setTimeout(closeOffer,1300)}catch(err){status.textContent=err.message||'No se ha podido enviar. Abriendo WhatsApp…';wa('Hola FÍBARO, quiero solicitar la oferta destacada: '+$('#offerModalTitle').textContent)}finally{btn.disabled=false;btn.textContent='Solicitar con prioridad'}};
const leadForm=$('#leadForm');let leadStarted=false;if(leadForm){leadForm.addEventListener('focusin',()=>{if(!leadStarted){leadStarted=true;track('funnel_started',{type:leadForm.dataset.campaignForm?'christmas_form':'general_form',page:location.pathname})}});leadForm.onsubmit=async e=>{e.preventDefault();const fd=new FormData(leadForm),status=$('#leadStatus'),btn=$('#leadSend'),originalService=String(fd.get('servicio')||'');if(originalService==='fiber_mobile'){fd.set('servicio','fiber');fd.set('funnel_context',JSON.stringify({campaign:'navidad2026',interest:'fibra_mas_movil'}))}else if(originalService==='company'){fd.set('servicio','callback');fd.set('funnel_context',JSON.stringify({campaign:'navidad2026',interest:'empresa'}))}if(leadForm.dataset.campaignForm){fd.set('funnel_detail','christmas_gift');fd.set('funnel_objective','gift_request')}fd.set('intent','web');fd.set('contact_preference','whatsapp');attribution(fd);const defaultLabel=btn.dataset.defaultLabel||btn.textContent;btn.disabled=true;btn.textContent='Enviando…';status.textContent='';try{const r=await send(INTAKE,fd);status.textContent=successMessage(r.reference||'');track('funnel_completed',{type:leadForm.dataset.campaignForm?'christmas_form':'general_form',service:fd.get('servicio'),page:location.pathname});leadForm.reset();leadStarted=false}catch(err){status.textContent=err.message||'No se ha podido enviar. Abriendo WhatsApp…';wa(leadForm.dataset.campaignForm?'Hola, vengo de la web y quiero información del regalo de Navidad 🎄':'Hola, vengo de la web y quiero información')}finally{btn.disabled=false;btn.textContent=defaultLabel}}}
$$('[data-open-general]').forEach((b,i)=>b.onclick=()=>{track('funnel_started',{type:'cta',placement:b.closest('section')?.id||`cta_${i}`});$('#contacto')?.scrollIntoView({behavior:'smooth'});setTimeout(()=>leadForm?.elements?.nombre?.focus(),400)});
})();
